---

networks:
  default:
    driver: bridge
    name: lab

services:
  gitlab:
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.demo.local/";
        prometheus_monitoring['enable'] = false;
    image: gitlab/gitlab-ce
    networks:
      default:
        aliases:
          - gitlab.demo.local
    ports:
      - "80:80"
      - "22:22"
    restart: unless-stopped
    stop_grace_period: 10m
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab

  # jenkins:
  #   container_name: jenkins
  #   environment:
  #     - JAVA_OPTS=-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-scripts; script-src 'unsafe-inline'; style-src 'unsafe-inline';" 
  #     - PLUGINS_FORCE_UPGRADE=true 
  #   image: jenkinsci/blueocean
  #   networks:
  #     default:
  #       aliases:
  #         - jenkins.demo.local
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   user: 501:20 # devops:docker usuario con permisos para crear contenedores
  #   volumes:
  #     - /etc/passwd:/etc/passwd:ro 
  #     - /Users/hugodiazgarcia/Proyectos/TMF/gitlabDocker/home/jenkins:/home/jenkins:rw 
  #     - /Users/hugodiazgarcia/Proyectos/TMF/gitlabDocker/var/jenkins_home:/var/jenkins_home:rw 
  #     - /var/run/docker.sock:/var/run/docker.sock:ro 

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

